name: senior_project
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev
publish_to: "none"

# App version
version: 1.0.0+1

# Dart SDK version
environment:
  sdk: ^3.7.2

# App dependencies
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# Flutter-specific configuration
flutter:
  uses-material-design: true

  assets:
    - assets/
